export type TaxMarket = {
  code: string;
  name: string;
  region: string;
  currency: string;
  indirectTaxName: string;
  standardRate: number;
  defaultDutyRate: number;
  eInvoiceStatus: string;
  sourceStatus: "official-seed" | "estimated-seed" | "manual-required";
  sourceUrl?: string;
  notes: string[];
};

export const RULE_PACK_VERSION = "global-indirect-tax-seed-2026.07.15";

export const EXPORT_MARKETS: TaxMarket[] = [
  {
    code: "BR",
    name: "Brasil",
    region: "América Latina",
    currency: "BRL",
    indirectTaxName: "ICMS/IPI/PIS/COFINS/ISS",
    standardRate: 0,
    defaultDutyRate: 0,
    eInvoiceStatus: "NF-e, NFC-e, NFS-e por adaptador Brasil",
    sourceStatus: "manual-required",
    notes: ["Calculo doméstico exige NCM, CFOP, CST/CSOSN, UF origem/destino, regime e município."],
  },
  {
    code: "US",
    name: "Estados Unidos",
    region: "América do Norte",
    currency: "USD",
    indirectTaxName: "Sales Tax",
    standardRate: 0,
    defaultDutyRate: 0.05,
    eInvoiceStatus: "state/local sales tax, nexus e marketplace facilitator",
    sourceStatus: "manual-required",
    notes: ["Não existe VAT federal. Sales tax depende de estado, cidade, county, produto e nexus."],
  },
  {
    code: "CA",
    name: "Canadá",
    region: "América do Norte",
    currency: "CAD",
    indirectTaxName: "GST/HST/PST/QST",
    standardRate: 0.05,
    defaultDutyRate: 0.06,
    eInvoiceStatus: "GST/HST por place-of-supply",
    sourceStatus: "official-seed",
    sourceUrl: "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/charge-collect-which-rate.html",
    notes: ["GST/HST varia por província/território; substitua a alíquota pelo destino real."],
  },
  {
    code: "MX",
    name: "México",
    region: "América Latina",
    currency: "MXN",
    indirectTaxName: "IVA",
    standardRate: 0.16,
    defaultDutyRate: 0.08,
    eInvoiceStatus: "CFDI por adaptador México",
    sourceStatus: "estimated-seed",
    notes: ["Pode haver taxa reduzida/fronteira, IEPS e regras CFDI por produto."],
  },
  { code: "AR", name: "Argentina", region: "América Latina", currency: "ARS", indirectTaxName: "IVA", standardRate: 0.21, defaultDutyRate: 0.12, eInvoiceStatus: "Factura electrónica", sourceStatus: "estimated-seed", notes: ["Pode envolver percepciones/retenciones e impostos provinciais."] },
  { code: "CL", name: "Chile", region: "América Latina", currency: "CLP", indirectTaxName: "IVA", standardRate: 0.19, defaultDutyRate: 0.06, eInvoiceStatus: "DTE", sourceStatus: "estimated-seed", notes: ["Classificação aduaneira e tratados podem alterar duty."] },
  { code: "CO", name: "Colômbia", region: "América Latina", currency: "COP", indirectTaxName: "IVA", standardRate: 0.19, defaultDutyRate: 0.1, eInvoiceStatus: "Factura electrónica DIAN", sourceStatus: "estimated-seed", notes: ["Pode haver retenciones e regimes especiais."] },
  { code: "PE", name: "Peru", region: "América Latina", currency: "PEN", indirectTaxName: "IGV", standardRate: 0.18, defaultDutyRate: 0.06, eInvoiceStatus: "Comprobante electrónico SUNAT", sourceStatus: "estimated-seed", notes: ["Duty depende de partida arancelaria."] },
  { code: "UY", name: "Uruguai", region: "América Latina", currency: "UYU", indirectTaxName: "IVA", standardRate: 0.22, defaultDutyRate: 0.08, eInvoiceStatus: "CFE", sourceStatus: "estimated-seed", notes: ["Pode haver alíquota mínima/reduzida por produto."] },
  { code: "PY", name: "Paraguai", region: "América Latina", currency: "PYG", indirectTaxName: "IVA", standardRate: 0.1, defaultDutyRate: 0.08, eInvoiceStatus: "SIFEN", sourceStatus: "estimated-seed", notes: ["Requer confirmação por regime/produto."] },
  { code: "EC", name: "Equador", region: "América Latina", currency: "USD", indirectTaxName: "IVA", standardRate: 0.15, defaultDutyRate: 0.1, eInvoiceStatus: "Comprobantes electrónicos SRI", sourceStatus: "estimated-seed", notes: ["Alíquota e ICE podem variar por produto."] },
  { code: "AG", name: "Antígua e Barbuda", region: "Caribe", currency: "XCD", indirectTaxName: "ABST", standardRate: 0.15, defaultDutyRate: 0.05, eInvoiceStatus: "commercial invoice/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; livre comércio depende de origem preferencial, HS code e acordo aplicável."] },
  { code: "BS", name: "Bahamas", region: "Caribe", currency: "BSD", indirectTaxName: "VAT", standardRate: 0.1, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARIFORUM EPA; Bahamas não integra a união aduaneira CARICOM. Validar regra de origem."] },
  { code: "BB", name: "Barbados", region: "Caribe", currency: "BBD", indirectTaxName: "VAT", standardRate: 0.175, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar origem preferencial e categoria do produto."] },
  { code: "DM", name: "Dominica", region: "Caribe", currency: "XCD", indirectTaxName: "VAT", standardRate: 0.15, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar certificado de origem e tratamento preferencial."] },
  { code: "DO", name: "República Dominicana", region: "Caribe", currency: "DOP", indirectTaxName: "ITBIS", standardRate: 0.18, defaultDutyRate: 0.06, eInvoiceStatus: "e-CF / DGII", sourceStatus: "estimated-seed", notes: ["CARIFORUM EPA e acordos regionais; validar regra de origem, canal e produto."] },
  { code: "GD", name: "Granada", region: "Caribe", currency: "XCD", indirectTaxName: "VAT", standardRate: 0.15, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar origem preferencial e classificação aduaneira."] },
  { code: "GY", name: "Guiana", region: "Caribe", currency: "GYD", indirectTaxName: "VAT", standardRate: 0.14, defaultDutyRate: 0.06, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; validar regra de origem e licença quando aplicável."] },
  { code: "HT", name: "Haiti", region: "Caribe", currency: "HTG", indirectTaxName: "TCA", standardRate: 0.1, defaultDutyRate: 0.06, eInvoiceStatus: "customs/commercial invoice", sourceStatus: "manual-required", notes: ["CARICOM/CARIFORUM; aplicação de preferências exige validação específica antes de cotar."] },
  { code: "JM", name: "Jamaica", region: "Caribe", currency: "JMD", indirectTaxName: "GCT", standardRate: 0.15, defaultDutyRate: 0.06, eInvoiceStatus: "GCT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar certificado de origem e item tributável."] },
  { code: "MS", name: "Montserrat", region: "Caribe", currency: "XCD", indirectTaxName: "Customs/consumption tax", standardRate: 0.15, defaultDutyRate: 0.05, eInvoiceStatus: "customs/commercial invoice", sourceStatus: "manual-required", notes: ["Membro CARICOM; preferências dependem de origem e regras locais do território."] },
  { code: "LC", name: "Santa Lúcia", region: "Caribe", currency: "XCD", indirectTaxName: "VAT", standardRate: 0.125, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar origem preferencial e categoria fiscal."] },
  { code: "KN", name: "São Cristóvão e Névis", region: "Caribe", currency: "XCD", indirectTaxName: "VAT", standardRate: 0.17, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; validar regra de origem e duty por HS code."] },
  { code: "VC", name: "São Vicente e Granadinas", region: "Caribe", currency: "XCD", indirectTaxName: "VAT", standardRate: 0.16, defaultDutyRate: 0.05, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar origem preferencial e exigências de importação."] },
  { code: "SR", name: "Suriname", region: "Caribe", currency: "SRD", indirectTaxName: "VAT", standardRate: 0.1, defaultDutyRate: 0.06, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; validar classificação, origem e tratamento preferencial."] },
  { code: "TT", name: "Trinidad e Tobago", region: "Caribe", currency: "TTD", indirectTaxName: "VAT", standardRate: 0.125, defaultDutyRate: 0.06, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["CARICOM/CARIFORUM; confirmar origem preferencial, licença e duty por produto."] },
  { code: "PT", name: "Portugal", region: "Europa", currency: "EUR", indirectTaxName: "IVA", standardRate: 0.23, defaultDutyRate: 0.04, eInvoiceStatus: "SAF-T/PT e faturacao certificada", sourceStatus: "estimated-seed", notes: ["Madeira/Acores e taxas reduzidas exigem regra propria."] },
  { code: "ES", name: "Espanha", region: "Europa", currency: "EUR", indirectTaxName: "IVA", standardRate: 0.21, defaultDutyRate: 0.04, eInvoiceStatus: "Factura electronica / SII", sourceStatus: "estimated-seed", notes: ["Canárias/Ceuta/Melilla usam regimes próprios."] },
  { code: "FR", name: "França", region: "Europa", currency: "EUR", indirectTaxName: "TVA", standardRate: 0.2, defaultDutyRate: 0.04, eInvoiceStatus: "e-invoicing France", sourceStatus: "estimated-seed", notes: ["Reduzidas e DOM exigem regra específica."] },
  { code: "DE", name: "Alemanha", region: "Europa", currency: "EUR", indirectTaxName: "USt/VAT", standardRate: 0.19, defaultDutyRate: 0.04, eInvoiceStatus: "eRechnung / XRechnung", sourceStatus: "estimated-seed", notes: ["B2B intra-EU pode usar reverse charge."] },
  { code: "IT", name: "Itália", region: "Europa", currency: "EUR", indirectTaxName: "IVA", standardRate: 0.22, defaultDutyRate: 0.04, eInvoiceStatus: "FatturaPA / SDI", sourceStatus: "estimated-seed", notes: ["Split payment e alíquotas reduzidas podem aplicar."] },
  { code: "NL", name: "Holanda", region: "Europa", currency: "EUR", indirectTaxName: "BTW", standardRate: 0.21, defaultDutyRate: 0.04, eInvoiceStatus: "Peppol/eInvoice", sourceStatus: "estimated-seed", notes: ["OSS/IOSS para B2C cross-border pode aplicar."] },
  { code: "BE", name: "Bélgica", region: "Europa", currency: "EUR", indirectTaxName: "BTW/TVA", standardRate: 0.21, defaultDutyRate: 0.04, eInvoiceStatus: "B2B e-invoicing planejado", sourceStatus: "estimated-seed", notes: ["Requer regra linguística e categoria fiscal."] },
  { code: "CH", name: "Suíça", region: "Europa", currency: "CHF", indirectTaxName: "MWST/TVA/IVA", standardRate: 0.081, defaultDutyRate: 0.04, eInvoiceStatus: "VAT e customs", sourceStatus: "estimated-seed", notes: ["Duty pode ser por peso/unidade, não só ad valorem."] },
  {
    code: "GB",
    name: "Reino Unido",
    region: "Europa",
    currency: "GBP",
    indirectTaxName: "VAT",
    standardRate: 0.2,
    defaultDutyRate: 0.04,
    eInvoiceStatus: "VAT + MTD",
    sourceStatus: "official-seed",
    sourceUrl: "https://www.gov.uk/vat-rates",
    notes: ["Taxas reduced/zero/exempt dependem do item; import VAT pode aplicar."],
  },
  { code: "IE", name: "Irlanda", region: "Europa", currency: "EUR", indirectTaxName: "VAT", standardRate: 0.23, defaultDutyRate: 0.04, eInvoiceStatus: "VAT / Peppol readiness", sourceStatus: "estimated-seed", notes: ["B2B intra-EU pode usar reverse charge."] },
  { code: "PL", name: "Polônia", region: "Europa", currency: "PLN", indirectTaxName: "VAT", standardRate: 0.23, defaultDutyRate: 0.04, eInvoiceStatus: "KSeF", sourceStatus: "estimated-seed", notes: ["KSeF e JPK exigem adaptador."] },
  { code: "SE", name: "Suécia", region: "Europa", currency: "SEK", indirectTaxName: "MOMS", standardRate: 0.25, defaultDutyRate: 0.04, eInvoiceStatus: "Peppol", sourceStatus: "estimated-seed", notes: ["Taxas reduzidas para alimentos/livros/transporte."] },
  { code: "NO", name: "Noruega", region: "Europa", currency: "NOK", indirectTaxName: "MVA", standardRate: 0.25, defaultDutyRate: 0.04, eInvoiceStatus: "EHF/Peppol", sourceStatus: "estimated-seed", notes: ["VOEC pode aplicar a e-commerce B2C."] },
  { code: "DK", name: "Dinamarca", region: "Europa", currency: "DKK", indirectTaxName: "MOMS", standardRate: 0.25, defaultDutyRate: 0.04, eInvoiceStatus: "NemHandel/Peppol", sourceStatus: "estimated-seed", notes: ["Poucas taxas reduzidas; confirmar produto."] },
  { code: "FI", name: "Finlândia", region: "Europa", currency: "EUR", indirectTaxName: "ALV", standardRate: 0.255, defaultDutyRate: 0.04, eInvoiceStatus: "Peppol", sourceStatus: "estimated-seed", notes: ["Standard seed deve ser confirmado por vigência."] },
  { code: "AT", name: "Áustria", region: "Europa", currency: "EUR", indirectTaxName: "USt", standardRate: 0.2, defaultDutyRate: 0.04, eInvoiceStatus: "e-Rechnung.gv.at", sourceStatus: "estimated-seed", notes: ["Taxas reduzidas para categorias específicas."] },
  { code: "CZ", name: "Tchéquia", region: "Europa", currency: "CZK", indirectTaxName: "DPH", standardRate: 0.21, defaultDutyRate: 0.04, eInvoiceStatus: "VAT reporting", sourceStatus: "estimated-seed", notes: ["Requer validação de alíquota reduzida."] },
  { code: "HU", name: "Hungria", region: "Europa", currency: "HUF", indirectTaxName: "AFA", standardRate: 0.27, defaultDutyRate: 0.04, eInvoiceStatus: "Online Szamla", sourceStatus: "estimated-seed", notes: ["Uma das maiores alíquotas padrão de VAT; confirmar categoria."] },
  { code: "RO", name: "Romênia", region: "Europa", currency: "RON", indirectTaxName: "TVA", standardRate: 0.19, defaultDutyRate: 0.04, eInvoiceStatus: "RO e-Factura", sourceStatus: "estimated-seed", notes: ["e-Factura exige adaptador local."] },
  { code: "GR", name: "Grécia", region: "Europa", currency: "EUR", indirectTaxName: "FPA", standardRate: 0.24, defaultDutyRate: 0.04, eInvoiceStatus: "myDATA", sourceStatus: "estimated-seed", notes: ["Ilhas podem ter tratamento específico."] },
  { code: "TR", name: "Turquia", region: "Europa/Ásia", currency: "TRY", indirectTaxName: "KDV", standardRate: 0.2, defaultDutyRate: 0.06, eInvoiceStatus: "e-Fatura/e-Arsiv", sourceStatus: "estimated-seed", notes: ["KDV e customs variam por produto/regime."] },
  { code: "CN", name: "China", region: "Ásia", currency: "CNY", indirectTaxName: "VAT", standardRate: 0.13, defaultDutyRate: 0.08, eInvoiceStatus: "fapiao", sourceStatus: "estimated-seed", notes: ["Fapiao e import duty exigem classificação HS."] },
  {
    code: "JP",
    name: "Japão",
    region: "Ásia",
    currency: "JPY",
    indirectTaxName: "Consumption Tax",
    standardRate: 0.1,
    defaultDutyRate: 0.04,
    eInvoiceStatus: "Qualified Invoice System",
    sourceStatus: "official-seed",
    sourceUrl: "https://www.nta.go.jp/english/taxes/consumption_tax/index.htm",
    notes: ["Ha taxa reduzida de consumo para certas categorias; confirmar produto."],
  },
  { code: "KR", name: "Coreia do Sul", region: "Ásia", currency: "KRW", indirectTaxName: "VAT", standardRate: 0.1, defaultDutyRate: 0.06, eInvoiceStatus: "e-Tax invoice", sourceStatus: "estimated-seed", notes: ["B2B e digital services exigem regra local."] },
  {
    code: "SG",
    name: "Singapura",
    region: "Ásia",
    currency: "SGD",
    indirectTaxName: "GST",
    standardRate: 0.09,
    defaultDutyRate: 0,
    eInvoiceStatus: "InvoiceNow / Peppol",
    sourceStatus: "official-seed",
    sourceUrl: "https://www.iras.gov.sg/taxes/goods-services-tax-(gst)/basics-of-gst/current-gst-rates",
    notes: ["GST zero-rated/exempt pode aplicar conforme supply."],
  },
  { code: "IN", name: "Índia", region: "Ásia", currency: "INR", indirectTaxName: "GST", standardRate: 0.18, defaultDutyRate: 0.1, eInvoiceStatus: "GST e-Invoice / IRP", sourceStatus: "estimated-seed", notes: ["GST tem slabs; importação pode envolver BCD e IGST."] },
  { code: "TH", name: "Tailândia", region: "Ásia", currency: "THB", indirectTaxName: "VAT", standardRate: 0.07, defaultDutyRate: 0.08, eInvoiceStatus: "e-Tax invoice", sourceStatus: "estimated-seed", notes: ["Duty e VAT por item."] },
  { code: "MY", name: "Malásia", region: "Ásia", currency: "MYR", indirectTaxName: "SST", standardRate: 0.08, defaultDutyRate: 0.06, eInvoiceStatus: "LHDN e-Invoice", sourceStatus: "estimated-seed", notes: ["SST não é VAT; pode variar por bem/serviço."] },
  { code: "ID", name: "Indonésia", region: "Ásia", currency: "IDR", indirectTaxName: "PPN", standardRate: 0.11, defaultDutyRate: 0.08, eInvoiceStatus: "e-Faktur", sourceStatus: "estimated-seed", notes: ["PPN e import duty exigem classificação local."] },
  { code: "HK", name: "Hong Kong", region: "Ásia", currency: "HKD", indirectTaxName: "No VAT/GST", standardRate: 0, defaultDutyRate: 0, eInvoiceStatus: "commercial invoice/customs", sourceStatus: "estimated-seed", notes: ["Sem VAT/GST geral; ainda pode haver duty/excise para itens específicos."] },
  { code: "AU", name: "Austrália", region: "Oceania", currency: "AUD", indirectTaxName: "GST", standardRate: 0.1, defaultDutyRate: 0.05, eInvoiceStatus: "Peppol eInvoicing", sourceStatus: "estimated-seed", notes: ["GST e import duty dependem de low value goods e tipo de supply."] },
  { code: "NZ", name: "Nova Zelândia", region: "Oceania", currency: "NZD", indirectTaxName: "GST", standardRate: 0.15, defaultDutyRate: 0.05, eInvoiceStatus: "eInvoicing", sourceStatus: "estimated-seed", notes: ["GST de low value imported goods pode aplicar."] },
  { code: "AE", name: "Emirados Árabes", region: "Oriente Médio", currency: "AED", indirectTaxName: "VAT", standardRate: 0.05, defaultDutyRate: 0.05, eInvoiceStatus: "FTA VAT / e-invoicing rollout", sourceStatus: "estimated-seed", notes: ["VAT e customs duty comuns; zonas francas podem alterar tratamento."] },
  { code: "SA", name: "Arábia Saudita", region: "Oriente Médio", currency: "SAR", indirectTaxName: "VAT", standardRate: 0.15, defaultDutyRate: 0.05, eInvoiceStatus: "ZATCA Fatoora", sourceStatus: "estimated-seed", notes: ["E-invoicing ZATCA exige adaptador próprio."] },
  { code: "QA", name: "Qatar", region: "Oriente Médio", currency: "QAR", indirectTaxName: "VAT planejado/limited", standardRate: 0, defaultDutyRate: 0.05, eInvoiceStatus: "customs/commercial invoice", sourceStatus: "manual-required", notes: ["VAT geral deve ser confirmado antes de cálculo real."] },
  { code: "IL", name: "Israel", region: "Oriente Médio", currency: "ILS", indirectTaxName: "VAT", standardRate: 0.18, defaultDutyRate: 0.06, eInvoiceStatus: "allocation number/e-invoicing", sourceStatus: "estimated-seed", notes: ["Alíquota padrão deve ser confirmada por vigência."] },
  { code: "ZA", name: "África do Sul", region: "África", currency: "ZAR", indirectTaxName: "VAT", standardRate: 0.15, defaultDutyRate: 0.08, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["Import VAT e customs duty exigem HS code."] },
  { code: "EG", name: "Egito", region: "África", currency: "EGP", indirectTaxName: "VAT", standardRate: 0.14, defaultDutyRate: 0.1, eInvoiceStatus: "ETA eInvoice", sourceStatus: "estimated-seed", notes: ["Pode haver schedule tax e customs por produto."] },
  { code: "MA", name: "Marrocos", region: "África", currency: "MAD", indirectTaxName: "TVA", standardRate: 0.2, defaultDutyRate: 0.1, eInvoiceStatus: "VAT/customs", sourceStatus: "estimated-seed", notes: ["Taxas reduzidas e duty por HS code."] },
];

export function getMarket(countryCode: string): TaxMarket | undefined {
  const normalized = countryCode.trim().toUpperCase();
  return EXPORT_MARKETS.find((market) => market.code === normalized);
}
